### ISSUE TITLE
ssh: connect to host <compute-0-12> port 22: Connection refused

### ISSUE THREAD

**Issue by caot** [sdsc/cluster-guide#5]
Here is the case. A new disk was installed in a node, so it is to reinstall the node. I tried the follows, however it shows up `ssh: connect to host compute-0-12 port 22: Connection refused`, however `ping` works. What could I do to make it work? It's rocks 6.1.1. Thanks. 

	# rocks set host boot compute-0-12 action=install
	# ipmitool -U hlmbmc -I lanplus -H ipmi-0-12 power on
	
	# ssh devel-server-0-12
	ssh: connect to host compute-0-12 port 22: Connection refused
	
	# ping compute-0-12
	PING compute-0-12.local (10.16.11.241) 56(84) bytes of data.
	64 bytes from compute-0-12.local (10.16.11.241): icmp_seq=1 ttl=64 time=0.217 ms
	64 bytes from compute-0-12.local (10.16.11.241): icmp_seq=2 ttl=64 time=0.203 ms
	^C
	--- compute-0-12.local ping statistics ---
	2 packets transmitted, 2 received, 0% packet loss, time 1694ms
	rtt min/avg/max/mdev = 0.203/0.210/0.217/0.007 ms

**Comment by tcooper** [comment]
This repository contains a guide to assist with setup of a Rocks 6 cluster and, frankly, is a bit out of date. A better place to get help with this node reinstallation issue is the Rocks Mailing List. You can find links to the list archives and subscription [here](http://www.rocksclusters.org/docs.html).
